### ISSUE TITLE
who delete dt files?

### ISSUE THREAD

**Issue by stefano-gurrieri** [ROJ-ITALY/test-ce#4]
Max,
who delete dtb files under / after EOL test?

Trying to follow your logic, at the end, under rootFS / we will have:
010100.dtb
010101.dtb
vdwcontroller.dtb set to (e.g) 010101.dtb (replaced after run update_bsp.sh)
zImage (replaced after run update_bsp.sh)

who delete 010100.dtb and 010101.dtb?

**Comment by mdekoninck** [comment]
you want to keep the other dtb files on roots?

**Comment by stefano-gurrieri** [comment]
no. At the end, we want keep under rootFS only vdwcontroller.dtb and zImage.
I had removed other dtb files in eeprom_data_china.py; have you removed this part?

**Comment by mdekoninck** [comment]
Let me check

**Comment by mdekoninck** [comment]
https://github.com/ROJ-ITALY/test-ce/commit/69cdaa7edf90f00fe51acf872bdb4abdcab2ac28#diff-fd96eb4810ba9a35f9dbe682c21b0038L26

here, i removed.
Actually you do not need to copy or other dtb files on the rootfs at ROJ. Beceause the new dtb files are stored on the production fallback stick so the correct one is copied from there (in the update_bsp.sh)

**Comment by stefano-gurrieri** [comment]
not proper. Currently, I need to copy 010100 and 010101 and set vdwcontroller at 010101.
This important for us, otherwise the procedure at the first boot doesn't start.
At the end of our functional test, we program eeprom and set vdwcontroller at 010100. So I need both files.
Anyway, Max, I think that is not a problem for you remove these files.

**Comment by mdekoninck** [comment]
ok i will remove them in update_bsp.sh

**Comment by mdekoninck** [comment]
should be fixed https://github.com/ROJ-ITALY/meta-vdw-prod/blob/dd494e49e6bf9ae88759ed4624fba8430bf07143/recipes-core/prod-users/prod-users/scripts/update_bsp.sh#L80

**Comment by stefano-gurrieri** [comment]
Max,
shouldn't mount $MOUNT_DESTINATIONDEVICE before to remove these dtb files?

**Comment by mdekoninck** [comment]
i yeah sorry (i did not have coffee yet)

**Comment by mdekoninck** [comment]
https://github.com/ROJ-ITALY/meta-vdw-prod/blob/5db6fe505403728c4451c0655b1647a459dcb3f5/recipes-core/prod-users/prod-users/scripts/update_bsp.sh#L80

**Comment by stefano-gurrieri** [comment]
:-)

When you have an image ready.... let me know that we want to try this image also here. I've done under work folder, a subfolder work_image_fbk_prod. Is it ok?

**Comment by mdekoninck** [comment]
ok, only have to do usb test, I think i can finish today I will let you know

**Comment by stefano-gurrieri** [comment]
Ok no problem.
